# Generated by Django 3.2.18 on 2023-05-07 03:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20230507_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
