# Generated by Django 4.2.1 on 2023-05-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_product_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('cost', models.FloatField()),
                ('content', models.ManyToManyField(to='frontend.product')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='purchases',
            field=models.ManyToManyField(blank=True, to='frontend.purchase'),
        ),
    ]
