# Generated by Django 4.2.1 on 2023-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_purchase_user_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_url',
            field=models.CharField(default='sdfsdf', max_length=2084),
        ),
    ]
